### ISSUE TITLE
Waterpipe client

### ISSUE THREAD

**Issue by silentiumNoxe** [silentiumNoxe/priest_feudal_back#1]
Create **lib-waterpipe** module.
This library should provide clients of Waterpipe and properties (`@ConfigurationProperties`)
The client works via gRPC, receives any payload, and sends requests specified in the protobuf.

[Java gRPC client (Baeldung)](https://www.baeldung.com/grpc-introduction)

```yaml
waterpipe:
  token: string
  addr: #waterpipe has many master services, and the client can connect to any of
    - ip1:8000
    - ip2:8000
    - ip3:10000
```

[Use this protobuf](https://github.com/silentiumNoxe/priest_feudal_back/files/12061174/openapi.txt) (Do not miss protobuf extension!)
Fields expect JSON payload.
